FORMAT: 1A

# DaTeAPI

CRUD-API för att schleppa data mellan databasen och webbsidan

# Group Pages
Sidor av olika slag på hemsidan. Mestadels statiska och alltid synliga.
## Alla pages [/pages]
### Lista alla pages [GET]
+ Response 200 (application/json)
## Page [/pages/{page_id}]
### Hämta just en viss sida [GET]
+ Response 200 (application/json)

# Group Posts

Inlägg på hemsidan. Sorteras på datum.

# Group Events

Händelser på den gamla hemsidan. Sitzer etc, med anmälningsformulär beskrivningar osv.

# Group Members

Medlemshantering.

# Group Assets

Statiska filer, bl.a. sitzbilder och tenter.

# Group r

Vem vet?